details/aplicatie1/urls.py
#urls secundare ale aplicatii adica o sa vina cu visualizations + delete/add/etc
from django.urls import path, include

from aplicatie1 import views
from .models import Visualization
app_name = 'visualizations'

# from django_downloadview import ObjectDownloadView
# download = ObjectDownloadView.as_view(model=Visualization, file_field='file')
urlpatterns = [

    path('', views.VisualizationsView.as_view(), name='lista_vizualizare'),
    path('adaugare/', views.CreateVisualizationsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateVisualizationsView.as_view(), name='modifica'), #il duc in index ca sa creez butonul
    path('<int:pk>/delete/', views.delete_visualizations, name='sterge'), #il duc in index ca sa creez butonul
    path('<int:pk>/activeaza/', views.activate_visualizations, name='activeaza'), #il duc in index ca sa creez butonul
    path('vizualizare_inactive', views.VisualizationsInactiveView.as_view(), name='vizualizare_inactive'), #il duc in base ca sa creez tab-ul
    path('deadline', views.Deadline.as_view(), name='deadline'), #il duc in base ca sa creez tab-ul
    path('expired', views.Expired.as_view(), name='expired'), #il duc in base ca sa creez tab-ul
    path('download/', views.download_file, name='download'),
    # path('download//', download, name='download'),

]

details/details/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from userprofile import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

# from userprofile.views import MyLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login', views.custom_login, name='login'),
    # path('logout', views.custom_logout, name='logout'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    # path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'), #este partea de logout veche
    # path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', views.my_login, name='login'),
    path('visualizations/', include('aplicatie1.urls')),
    # path('profile/', include('userprofile.urls')), #am comentat cand am facut noul virtual venv, totul merge ok
    path('userprofile/', include('userprofile.urls'), name='userprofile'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

details/aplicatie1/models.py
from django.db import models

status_choices = (("Started", "Started"), ("Done", "Done"), ("Not started", "Not started"))
percentage_choices = (
("0%", "0%"), ("10%", "10%"), ("20%", "20%"), ("30%", "30%"), ("40%", "40%"), ("50%", "50%"), ("60%", "60%"),
("70%", "70%"), ("80%", "80%"), ("90%", "90%"), ("100%", "100%"))
from django.contrib.auth.models import User

# Create your models here.
class Visualization(models.Model):
    project = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    responsible = models.CharField(max_length=100)
    deadline = models.CharField(max_length=10)
    status = models.CharField(max_length=20, choices=status_choices, default="Not started")
    percentage = models.CharField(max_length=20, choices=percentage_choices, default="0%")
    comment = models.CharField(max_length=1000, default="To be modified")
    active = models.BooleanField(default=0)
    file = models.FileField(upload_to='store/', default="No file")
    # abc = models.CharField(max_length=100, default="Empty") #creez un camp nou, fac makemigrations, si apare la migrations 0002, apoi vreau sa sterg acest camp, rulez make migrations, apare 0003 si imi spune ca le-a sters
    #daca adaug un camp noi si ii dau migrate, in maria db ar treubi sa vad noul camp in tabelul meu describe aplicatie1_visualization, in maria db: describe describe aplicatie1_visualization
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    # read about ORM; One-to-Many relations, Many-to-Many, One-to-One. Normal form 3.
    # create a relation between Visualization model and auth_user model.

    def __str__(self):
        return f'{self.project} - {self.description} - {self.responsible} - {self.deadline}' \
               f'- {self.status} - {self.percentage} - {self.comment} - {self.file}'

details/aplicatie1/views.py
import mimetypes
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.shortcuts import render, redirect
import datetime
from .filters import VisualizationFilter
# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from aplicatie1.models import Visualization
from .functions import handle_uploaded_file
import os


class VisualizationsView(LoginRequiredMixin, ListView):
    model = Visualization
    template_name = 'aplicatie1/visualizations_index.html'
    # paginate_by = 4
    today = datetime.date.today()
    queryset = model.objects.filter(active=1).filter(deadline__gte=today).order_by('project')
    context_object_name = 'visualizations'

    def get_context_data(self, *args, **kwargs):
        data = super(VisualizationsView, self).get_context_data(*args, **kwargs)
        data['filter'] = VisualizationFilter(self.request.GET, queryset=self.get_queryset())
        return data

class CreateVisualizationsView(LoginRequiredMixin, CreateView):
    model = Visualization
    fields = ['project', 'description', 'responsible', 'deadline', 'status', 'percentage', 'comment', 'file', 'author'] #ce campuri sa aduca din model
    template_name = 'aplicatie1/visualizations_form.html'#template-ul catre care trimitem

    def index(request):
        if request.method == 'POST':
            abc = Visualization(request.POST, request.FILES)
            if abc.is_valid():
                handle_uploaded_file(request.FILES['file'])
                return HttpResponse("File uploaded successfuly")
        else:
            abc = Visualization()
            return render(request, "visualizations_form.html", {'form': abc})
    def get_success_url(self):
        return reverse('visualizations:lista_vizualizare') #luat din urls, catre ce pagina sa ne trimita dupa ce adaugam datele

class UpdateVisualizationsView(LoginRequiredMixin, UpdateView):
    model = Visualization #luat din models si il importam
    fields = ['project', 'description', 'responsible', 'deadline', 'status', 'percentage', 'comment', 'file', 'author'] #ce campuri sa aduca din model
    template_name = 'aplicatie1/visualizations_form.html'#template-ul catre care trimitem


    def get_success_url(self):
        return reverse('visualizations:lista_vizualizare') #luat din urls, catre ce pagina sa ne trimita dupa ce adaugam datele

@login_required
def delete_visualizations(request, pk):
    Visualization.objects.filter(id=pk).update(active=0)
    return redirect('visualizations:lista_vizualizare')


@login_required
def activate_visualizations(request, pk):
    Visualization.objects.filter(id=pk).update(active=1)
    return redirect('visualizations:lista_vizualizare')

class VisualizationsInactiveView(LoginRequiredMixin, ListView):
    model = Visualization #luat din models si il importam
    template_name = 'aplicatie1/visualizations_index.html'
    # paginate_by = 4
    today = datetime.date.today()
    queryset = model.objects.filter(active=0).filter(deadline__gte=today).order_by('project')
    context_object_name = 'visualizations'

    def get_context_data(self, *args, **kwargs):
        data = super(VisualizationsInactiveView, self).get_context_data(*args, **kwargs)
        data['filter'] = VisualizationFilter(self.request.GET, queryset=self.get_queryset())
        return data

from datetime import timedelta

class Deadline(LoginRequiredMixin, ListView):
    model = Visualization
    template_name = 'aplicatie1/visualizations_index.html'
    today = datetime.date.today()
    next = datetime.date.today() + timedelta(days=7)
    queryset = model.objects.filter(deadline__lte=next).filter(deadline__gte=today)
    # print(queryset)
    # paginate_by = 4
    context_object_name = 'visualizations'

    def get_context_data(self, *args, **kwargs):
        data = super(Deadline, self).get_context_data(*args, **kwargs)
        data['filter'] = VisualizationFilter(self.request.GET, queryset=self.get_queryset())
        return data

class Expired(LoginRequiredMixin, ListView):
    model = Visualization
    template_name = 'aplicatie1/visualizations_index.html'
    today = datetime.date.today()
    try:
        # date = Visualization.objects.values('deadline').first()['deadline']
        queryset = model.objects.filter(deadline__lte=today)
        # print(queryset)
        # paginate_by = 4
        context_object_name = 'visualizations'
    except Exception:
        print("eroare")

    def get_context_data(self, *args, **kwargs):
        data = super(Expired, self).get_context_data(*args, **kwargs)
        data['filter'] = VisualizationFilter(self.request.GET, queryset=self.get_queryset())
        return data

def download_file(request, filename=''):
    if filename != '':
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        filepath = BASE_DIR + '/media/store/' + filename
        path = open(filepath, 'rb')
        mime_type, _ = mimetypes.guess_type(filepath)
        response = HttpResponse(path, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return redirect('visualizations:lista_vizualizare')

details/templates/aplicatie1/visualizations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }} {{ field.errors }} <br><br>
        {% endfor %}
        <button type="submit">Save</button>
    </form>
{% endblock %}

details/templates/aplicatie1/visualizations_index.html
{% extends 'base.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="containter">
    <form method="GET">
        {{ filter.form }}
        <button type="submit" class="btn btn-primary">Search</button>
    </form>

    <br>
    <table class="table table-hover">
        <a class="btn btn-success" href="{% url 'visualizations:adauga' %}  ">Add proiect</a>
        <thead>
        <tr>
            <th>Index</th>
            <th>Project name</th>
            <th>Description</th>
            <th>Responsible</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Percentage</th>
            <th>Comment</th>
            <th>Stare</th>
            <th>File</th>
            <th>Author</th>
            <th>Actions</th>

        </tr>
        </thead>
        <tbody>
        {% for item in filter.qs %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ item.project }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.responsible }}</td>
            <td>{{item.deadline}}</td>
            <td>{{item.status}}</td>
            <td>{{item.percentage}}</td>
            <td>{{item.comment}}</td>
            <td>{% if item.active == 1 %}
                <span>Activ</span>
                {% else %}
                <span>Inactiv</span>
                {% endif %}
            </td>
            <td>{{item.file}}</td>
            <td>{{item.author}}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">

                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'visualizations:modifica' item.id %}">Modify </a>
                        {% if item.active == 1 %}
                        <a class="dropdown-item" href="{% url 'visualizations:sterge' item.id %}">Deactivate</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'visualizations:activeaza' item.id %}">Activate</a>
                        {% endif %}
<!--                        <a class="dropdown-item" href="{% url 'visualizations:download' %}">Download</a>-->
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<!--{% if is_paginated %}-->
<!--<ul class="pagination">-->
<!--    {% if page_obj.has_previous %}-->
<!--    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>-->
<!--    {% else %}-->
<!--    <li class="disabled btn"><span><<</span></li>-->
<!--    {% endif %}-->
<!--    {% for i in paginator.page_range %}-->
<!--    {% if page_obj.number == i %}-->
<!--    <li class="active btn btn-success"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>-->
<!--    {% else %}-->
<!--    <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>-->
<!--    {% endif %}-->
<!--    {% endfor %}-->
<!--    {% if page_obj.has_next %}-->
<!--    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>-->
<!--    {% else %}-->
<!--    <li class="disabled btn"><span>>></span></li>-->
<!--    {% endif %}-->
<!--    <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of-->
<!--            {{ page_obj.paginator.count }}</span>-->
<!--</ul>-->
{% else %}
{% endif %}
{% endif %}
{% endblock %}