comparison/comparison/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('scraper/', include('scraper.urls'))
]
#done

comparison/scraper/urls.py
from django.urls import path, include

from . import views


app_name = 'scraper'

urlpatterns = [
    path('', views.SearchView.as_view(), name='search_view'),
    path('result/', views.ResultView.as_view(), name='result'),
]

#done

comparison/scraper/models.py
from django.db import models

class Products(models.Model):
    objects = None
    product_code = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    altex_price = models.CharField(max_length=100)
    active = models.BooleanField(default=1)
    emag_price = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)  #null = True to ImageField will enable it to store empty values as NULL for that table in relational database. blank= True If True, the field is allowed to be blank
    url_altex = models.URLField(null=True, blank=True)  # same as imagiefield
    url_emag = models.URLField(null=True, blank=True)  # same as imagiefield

    def __str__(self):
        return f'{self.product_code}'

#done

comparison/scraper/views.py
from django.shortcuts import render
class SearchView:
    pass

class ResultView:
    pass

comparison/templates/altex_vs_emag/search_product.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
    <div>
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}
            {% if field.label == "product_code" %}
            {% endif %}
        {% endfor %}
        <button class="btn btn-primary">Search product</button>
    </div>
    </center>
    </form>
{% endblock %}

<!--#done-->

comparison/templates/base.html
<html>
<head>
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body style="background-color:#FFFAFA">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <span>Hi,</span>
                    <a class="btn btn-primary" href="/scraper/">Search</a>
                    <a class="btn btn-primary" href="/admin">Admin</a>
                    <a class="btn btn-primary" href="{% url 'scraper:result' %}">Results</a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                </nav>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>