details/aplicatie1/urls.py
#urls secundare ale aplicatii adica o sa vina cu visualizations + delete/add/etc
from django.urls import path, include

from aplicatie1 import views
from .models import Visualization
app_name = 'visualizations'

# from django_downloadview import ObjectDownloadView
# download = ObjectDownloadView.as_view(model=Visualization, file_field='file')
urlpatterns = [

    path('', views.VisualizationsView.as_view(), name='lista_vizualizare'),
    path('adaugare/', views.CreateVisualizationsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateVisualizationsView.as_view(), name='modifica'), #il duc in index ca sa creez butonul
    path('<int:pk>/delete/', views.delete_visualizations, name='sterge'), #il duc in index ca sa creez butonul
    path('<int:pk>/activeaza/', views.activate_visualizations, name='activeaza'), #il duc in index ca sa creez butonul
    path('vizualizare_inactive', views.VisualizationsInactiveView.as_view(), name='vizualizare_inactive'), #il duc in base ca sa creez tab-ul
    path('deadline', views.Deadline.as_view(), name='deadline'), #il duc in base ca sa creez tab-ul
    path('expired', views.Expired.as_view(), name='expired'), #il duc in base ca sa creez tab-ul
    path('download/', views.download_file, name='download'),
    # path('download//', download, name='download'),

]

details/details/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from userprofile import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

# from userprofile.views import MyLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login', views.custom_login, name='login'),
    # path('logout', views.custom_logout, name='logout'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    # path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'), #este partea de logout veche
    # path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', views.my_login, name='login'),
    path('visualizations/', include('aplicatie1.urls')),
    # path('profile/', include('userprofile.urls')), #am comentat cand am facut noul virtual venv, totul merge ok
    path('userprofile/', include('userprofile.urls'), name='userprofile'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"), name="password_reset_complete"),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

details/userprofile/urls.py
from django.urls import path
from .views import MyPasswordChangeView, MyPasswordResetDoneView
from userprofile import views
from django.contrib.auth import views as auth_views
app_name = 'userprofile'

urlpatterns = [
    path('new_account/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
    path('change-password/', MyPasswordChangeView.as_view(), name='password-change-view'),
    path('change-password/done/', MyPasswordResetDoneView.as_view(), name='password-change-done-view'),
]

details/templates/base.html
{%load static%}
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <head>
    {% block title %}
    {% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel = "stylesheet" type="text/css" media="screen" href= "{%static 'main.css'%}">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    </head>
    <body style="background-image: url('https://img.freepik.com/free-vector/copy-space-wavy-white-background-layers_23-2148845469.jpg?w=2000');>">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <a class="btn" href="/admin">Admin</a>
                    {% if request.user.is_authenticated %}
                    <span>Hi, {{ request.user.username}} <i class="bi bi-person-workspace"></i></span>
                    <br><br>
                    <a href="{% url 'visualizations:lista_vizualizare' %}"><button class="btn"> <i class="bi bi-clipboard-pulse"></i> Active projects</button></a>
                    <a href="{% url 'visualizations:vizualizare_inactive' %}"><button class="btn"> <i class="bi bi-clipboard"></i> Inactive projects</button></a>
                    <a href="{% url 'visualizations:deadline' %}"><button class="btn"> <i class="bi bi-clock"></i> Close to deadline</button></a>
                    <a href="{% url 'visualizations:expired' %}"><button class="btn"> <i class="bi bi-clipboard2-x-fill"></i> Expired projects</button></a>
                    <a href="{% url 'userprofile:utilizator_nou' %}"><button class="btn"><i class="bi bi-person-plus-fill"></i> Add new user</button></a>
                    <a href="{% url 'userprofile:password-change-view' %}"><button class="btn"><i class="bi bi-key"></i> Change password</button></a>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                {% endif %}

                    </nav>
            </div>
        </div>
    </div>
    <br>
    {% block content %}
    {% endblock %}
    </body>

</html>

details/templates/password_reset.html
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<style>
h3 {
  text-align: center;
}
</style>
<h3>Password reset</h3>
<p style="text-align:center">Forgotten your password?</p>
<p style="text-align:center">Enter your email address bellow, and we'll email instructions for setting a new one</p>
<form align="center" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="Submit" name="Send email">
    <br>
    <br>
    <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://thehackernews.com/images/-B3mNhF5NHew/YJkiZd_XHsI/AAAAAAAABAc/tanw21tUN8Ykp4QNgTsn4aEpjtLf1eOnQCLcBGAsYHQ/s0/password.jpg"
          alt="" width="280" height="150"/>
      </div>
</form>

details/templates/password_reset_done.html
<h3>Password reset complete </h3>

<p> Your password has been set. You may go ahead and log in now </p>
<a href="/" class="btn btn-info">Log in</a>

details/templates/password_reset_form.html
<h3>Enter new password</h3>
<p>Please enter you now password twice so we can verify you typed it in correcly</p>
<form method="POST">

    {% csrf_token %}
    {{ form }}
    <input type="Submit" name="Update Password">
</form>

details/templates/password_reset_sent.html
<h3>Password reset sent </h3>

<p> We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. </p>

<p> If you don't receive an email, please make sure you're entered the address you registered with, and check you spam folder </p>